### ISSUE TITLE
Autogenerate publishers file

### ISSUE THREAD

**Issue by quentindecock** [promiscuous-io/promiscuous#34]
(cc @arjunanand ) Many times we devs change the `config/publishers.rb` file and forget to run the command `be promiscuous mocks -o gem/crowdtap/publishers.rb` to generate the publishers file that really matters. I would like this to be auto generated when the `config/publishers.rb` file is saved

**Comment by nviennot** [comment]
I recommend not to use `config/publishers.rb` and put the definitions directly in the models (like the subscribers) with `publish` blocks to avoid the confusion. But @kareemk disagrees on this point as he prefers to put the promiscuous definitions outside the models, a bit like `config/routes.rb`

If you'd like to have the gem/*/publisher.rb file to be auto generated when `config/publishers.rb` is saved, you can tweak your vim config to do so. That seems to be a little extreme thought (generating this file takes a certain amount of time, due to the loading of the application).

Note: I'm not very familiar with the workflow that is applied in practice, so it's hard for me to advise for a good solution.

**Comment by kareemk** [comment]
Proposed solution:
1. Add a config attribute for the location of the mock file
2. Hook into Kernel.at_exit and generate (as well as not require location from promiscuous command line)

**Comment by nviennot** [comment]
1. seems reasonable
2. is a bit magic as it would start writing files in your codebase when you close your rails console, which is very surprising IHMO.

A `guard` would be more appropriate I think, a bit like guard-livereload, or guard-sass. After all, it's not that different from generating assets.

**Comment by nviennot** [comment]
sass has a --watch option. We could also implement that:

```
promiscuous mocks -o ./gem/crowdtap/publishers.rb --watch
```

which would watch for relevant files to changes and regenerate the publishers file. To be plugged in the Procfile (similarly to guard)

**Comment by kareemk** [comment]
@nviennot that's perfect
