### ISSUE TITLE
Compatibility with Rails 4.0 and Mongoid 4.0

### ISSUE THREAD

**Issue by yodarjun** [promiscuous-io/promiscuous#36]
When using Rails 4 and mongoid, we're forced to use the master branch of mongoid (4.0.0). When using this setup, promiscuous doesn't seem to be throwing calling callbacks(after_create/after_save...) on the models that subscribe to published fields.

**Comment by AnneTheAgile** [comment]
Since this ticket was opened, a nice blog post discussed Mongoid v4 fixes required. Quick notes on the v3 items affected;  
1.Moped::BSON; 
2.Observers are deprecated in 4.0, eg Moped::BSON::ObjectId.legal?(id); 
3.Can no longer convert a string into a Moped::BSON::ObjectId(id).
http://artsy.github.io/blog/2013/11/07/upgrading-to-mongoid4/

It seems like the code base does indeed have issues on this score. I'm not sure how fast I'd be but it would be fun to set up a nice VM to test this out for you. I'm job hunting so I am trying to figure  out some nice ways to show my work. I just deleted Boxen though, I snafu'ed it!

**Comment by kareemk** [comment]
thanks @AnneTheAgile, that is helpful
