### ISSUE TITLE
Consider changing the name and logo

### ISSUE THREAD

**Issue by alex** [promiscuous-io/promiscuous#39]
I'm not sure if you're aware of this, but the unnecessary sexualization of this projects name and logo are a large distraction for many people, and serve to make this library (and the broader community) less welcoming.

Consider changing the name and logo to something more appropriate.

**Comment by veloper** [comment]
I've used, support, and really believe in this approach -- it's awesome in so many ways.  That said, I've personally been running into very skeptical opposition from colleagues while attempting to explain this approach and the benefits of doing so. (Solving a problem that no one realized they had.)

When I walked into the presentation at RubyConf the first thing I noticed was the cheeky logo that kind of made me stop and say... huh 0.o? I didn't make the connection to "RabbitMQ + Replication of Models" until a couple of days later when I went back to the project and noticed the tag line. I think my perception might have been due to the combination of the Logo reenforcing the Name's derogatory form  -- see attached definition.

![screen shot 2013-11-12 at 10 27 26 am](https://f.cloud.github.com/assets/340358/1522921/4c5c8d94-4baf-11e3-9d91-e64d8d6d8bf6.png)

If the Logo was changed to represent the action (pub/sub model replication between application) vs. the technology used (RabbitMQ) it may help to lessen some of the negative connotations.

**Comment by nviennot** [comment]
We are definitely going to change the logo to something more appropriate.
Regarding the name, we think that promiscuous is fine. it's a term used in software e.g. putting your network card in promiscuous mode to listen to all the incoming traffic.

Thank you for the constructing feedback :)

**Comment by andyl** [comment]
Caremad neo-puritans are on the march.

**Comment by kareemk** [comment]
Logo removed until we "commission" a new one
