### ISSUE TITLE
Adapter for queue

### ISSUE THREAD

**Issue by fatum** [promiscuous-io/promiscuous#49]
Do you have plan for supports another queues (aws sqs, redis-based (sidekiq, resque ets))?

**Comment by kareemk** [comment]
We don't currently. Why would you like to see other queue support?

**Comment by fatum** [comment]
We use aws sqs instead amqp :)

**Comment by kareemk** [comment]
This is not part of our near-term roadmap as getting rabbit setup in AWS is easy e.g. http://bigwig.io/, http://www.cloudamqp.com/.

**Comment by nathanpalmer** [comment]
So we're hesitant to bring on another queue dependency in our stack by requiring RabbitMq when we already have one via Sidekiq/Redis. While it isn't a huge deal it does mean it's an extra thing that we have to deploy, maintain and install on the development machines.

It would certainly be interesting to see this project support redis storage and redis queue to remove that dependency.. even in an optional format (such as a redis adapter.)

**Comment by fatum** [comment]
I've started simple library for state replication https://github.com/fatum/replicator

Sorry for bad english description in README :(

**Comment by kareemk** [comment]
@nathanpalmer redis is not durable and hence cannot guarantee delivery. rabbit on the otherhand has very strong semantics/gurantees. Is your application tolerant to data inconsistencies across applications?

@fatum nice work. you should make sure to document what guarantees your library offers. i say that because we worked really hard to ensure that ANY change to the DB, even by accessing the driver itself WILL eventually get published and replicated. For data its very important to know whether or not data loss can happen so that the developer can consider those failure scenarios.
