### ISSUE TITLE
Issues with 1.0.0 beta 5

### ISSUE THREAD

**Issue by AdamKyle** [promiscuous-io/promiscuous#62]
I have found the following issues upgrading to 1.0.0 beta 5 (can I suggest you move to a tag based system so that people testing or using can move back a version, I upgraded from 1.0.0 beta 2)
# Bundle Exec No loner works

I run this, when I update my apps that I am building:

`bundle exec promiscuous publish "Xaaron::User.all"`

Which spits out:

```
ArgumentError: wrong number of arguments (0 for 1)                                                 | 0/3  ETA: ??:??:??
--------------------------------------------------------------------------------
/Users/Adam/.rvm/gems/ruby-2.1.1/bundler/gems/promiscuous-5eddd5bc57e7/gemfiles/lib/promiscuous/publisher/model/base.rb:43:in `sync'
```

Which is: [base.rb#L43](https://github.com/promiscuous-io/promiscuous/blob/master/lib/promiscuous/publisher/model/base.rb#L43)

are we suppose to supply an additional argument? Because this has always worked for me before hand. It would always do:

```
Xaaron::User         |============================================================================>| 4/4 Time: 00:00:00
```

**Comment by kareemk** [comment]
This is fixed by f4aec9457b6399630be0a5db93929ac93d9ec5c9. I'll also soon have support for another attribute which will let you specify the target app name that you want to sync to so that you can avoid sending having all subscribers consume sync messages unnecessarily. 

I'll start using tags when I release 1.0.0 which should happen fairly soon.
